apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mistral-hf-tgi
  namespace: openshift-gitops
spec:
  destination:
    namespace: llms-test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: hg-tgi/overlays/mistral-test
    repoURL: https://github.com/erkerc/hftgi-llms.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
