apiVersion: dashboard.opendatahub.io/v1alpha
kind: AcceleratorProfile
metadata:
  name: nvidia-gpu-profile
  namespace: redhat-ods-applications
spec:
  displayName: NVIDIA GPU accelerator
  description: NVIDIA GPU accelerator
  enabled: true
  identifier: nvidia.com/gpu
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists